services:
  spring-e-com:
    build: .
    container_name: spring-e-com
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - PORT=${PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_DRIVER=${DB_DRIVER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
