spring.application.name=Spring e-com
spring.config.import=optional:file:.env[.properties]

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}